### ISSUE TITLE
License File missing

### ISSUE THREAD

**Issue by realvictorprm** [OptimisticPeach/GardeningGame#2]
Hi! :)

I just found this nice repo, because I was also looking into, [how to add content dynamically to MonoGame (at runtime)](https://community.monogame.net/t/building-and-loading-content-at-runtime/10849/8).

Do you mind adding a License to this repository?

My personal favourites would be MIT or Apache 2 🙈 However it's your decision of course :)

**Comment by OptimisticPeach** [comment]
Hi there @realvictorprm!

I just pushed two commits (one for master branch, one for cleaned branch) that should dual license to MIT and Apache 2.0 at your discretion.

Enjoy!

**Comment by realvictorprm** [comment]
Hi @OptimisticPeach :)
This is great, thank you very very much!
